concurrency:
	xcodebuild test \
	-project EnergyBenchmarks.xcodeproj \
	-scheme 'EnergyBenchmarks' \
	-destination "platform=iOS,name=Vitor’s iPhone" \
	-only-testing:EnergyBenchmarksTests/ConcurrencyBenchmarks